<a href="https://colab.research.google.com/github/asheerali/PyTorch_Tutorails/blob/main/Intro_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torch.utils.data
import torchvision.transforms as Transforms

torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [ ]:
torch.rand([2,2])

tensor([[0.6323, 0.9375],
        [0.3197, 0.2273]])

In [ ]:
a = torch.rand([3,5])
a.shape

torch.Size([3, 5])

In [ ]:
b = torch.rand([3,5])
a*b

tensor([[0.2149, 0.4602, 0.8359, 0.1678, 0.0830],
        [0.4346, 0.5172, 0.0173, 0.0410, 0.2278],
        [0.3467, 0.7287, 0.3384, 0.1191, 0.0967]])

In [ ]:
np_zero = np.zeros([2,2])
np_one = np.ones([2,2])
np_identity = np.identity(2)
zero = torch.zeros([2,2])
one = torch.ones([2,2]) 
identity = torch.eye(2)
print(zero)
print(one)
print(identity)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 0.],
        [0., 1.]])


In [ ]:
d_torch = torch.from_numpy(np_identity)
print(d_torch)
d_np = identity.numpy()
print("\n\n\n")
print(d_np)

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)




[[1. 0.]
 [0. 1.]]


In [ ]:
import torch
import torch.nn as nn

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(10, 20)
    self.fc2 = nn.Linear(20, 20)
    self.output = nn.Linear(20, 4)

  def forward(self, x):
    x =self.fc1(x)
    x = self.fc2(x)
    x = self.output(x)
    return x

In [ ]:
input_layer = torch.rand(10)
net = Net()
result = net(input_layer)

In [ ]:
print(result)

tensor([ 0.2670, -0.1889,  0.0299,  0.4804], grad_fn=<AddBackward0>)


In [ ]:
import torch
import torchvision
import torch.utils.data
import torchvision.transforms as transforms

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.4914, 0.48216, 0.44653),
                          (0.24703, 0.24349, 0.26159))]
)

In [ ]:
transform

Compose(
    ToTensor()
    Normalize(mean=(0.4914, 0.48216, 0.44653), std=(0.24703, 0.24349, 0.26159))
)

In [ ]:
trainset = torchvision.datasets.CIFAR10(root = './data', train = True,
                                        download = True, transform = transform)

testset = torchvision.datasets.CIFAR10(root = './data', train = False,
                                        download = True, transform = transform)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [ ]:
trainloader = torch.utils.data.DataLoader(trainset, batch_size= 32,
                                          shuffle = True, num_workers=4)

testloader = torch.utils.data.DataLoader(testset, batch_size= 100,
                                          shuffle = False, num_workers=4)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:566: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


Inspecting the dataloader

In [ ]:
print(testloader.dataset, trainloader.dataset)
print(testloader.batch_size)

Dataset CIFAR10
    Number of datapoints: 10000
    Root location: ./data
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.4914, 0.48216, 0.44653), std=(0.24703, 0.24349, 0.26159))
           ) Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.4914, 0.48216, 0.44653), std=(0.24703, 0.24349, 0.26159))
           )
100


In [ ]:
print(trainloader.sampler)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(32 * 32 * 3, 500)
    self.fc2 = nn.Linear(500, 10)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = self.fc2(x)
    return x

In [ ]:
net = Net()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=3e-4)

for epoch in range(10): # loop over the dataset multiple times 
  for i, data in enumerate(trainloader, 0):
    # Get the inputs
    inputs, labels = data
    inputs = inputs.view(-1, 32*32*3)

    # Zero the paramater gradients
    optimizer.zero_grad()

    #forward + backward + optimize
    outputs = net(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()

eveluation

In [ ]:
from prompt_toolkit import output
correct, total = 0, 0
predictions = []
net.eval()

for i, data in enumerate(trainloader, 0):
  # Get the inputs
  inputs, labels = data
  inputs = inputs.view(-1, 32*32*3)
  outputs = net(inputs)
  _, predicted = torch.max(outputs.data, 1)
  predictions.append(outputs)
  total += labels.size(0)
  correct += (predicted == labels).sum().item()

print('The testing set accuracy of the network in; %d %%' % (100*correct/ total))

The testing set accuracy of the network in; 72 %


Convolutions in PyTorch

In [ ]:
import torch
import torch.nn as nn

image = torch.rand(16, 3, 32, 32)
conv_filter = torch.nn.Conv2d(in_channels=3,
                              out_channels=1, kernel_size=5,
                              stride=1, padding=0)
output_feature = conv_filter(image)

print(output_feature.shape)

torch.Size([16, 1, 28, 28])


In [ ]:
import torch
import torch.nn.functional as F

image = torch.rand(16, 3, 32, 32)
filter = torch.rand(1, 3, 5, 5)
out_feat_F = F.conv2d(image, filter, stride=1, padding=0)

print(out_feat_F.shape)

torch.Size([16, 1, 28, 28])


Average Pooling in Torch

In [ ]:
im = torch.Tensor([[[[3,1,3,5],[6,0,7,9],[3,2,1,4],[0,2,4,3]]]])
avg_pooling = torch.nn.AvgPool2d(2)
output_feature = avg_pooling(im)

print(output_feature)

tensor([[[[2.5000, 6.0000],
          [1.7500, 3.0000]]]])


In [ ]:
im = torch.Tensor([[[[3,1,3,5],[6,0,7,9],[3,2,1,4],[0,2,4,3]]]])
output_features_F = F.avg_pool2d(im,2)

print(output_features_F)

tensor([[[[2.5000, 6.0000],
          [1.7500, 3.0000]]]])


AlexNet

In [ ]:
class AlexNet(nn.Module):
  def __init__(self, num_classes=1000):
    super(AlexNet, self).__init__()        
    self.conv1 = nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2)        
    self.relu = nn.ReLU(inplace=True)        
    self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2)        
    self.conv2 = nn.Conv2d(64, 192, kernel_size=5, padding=2)        
    self.conv3 = nn.Conv2d(192, 384, kernel_size=3, padding=1)        
    self.conv4 = nn.Conv2d(384, 256, kernel_size=3, padding=1)        
    self.conv5 = nn.Conv2d(256, 256, kernel_size=3, padding=1)        
    self.avgpool = nn.AdaptiveAvgPool2d((6, 6))        
    self.fc1 = nn.Linear(256 * 6 * 6, 4096)        
    self.fc2 = nn.Linear(4096, 4096)        
    self.fc3 = nn.Linear(4096, num_classes)

  def forward(self, x):        
    x = self.relu(self.conv1(x))        
    x = self.maxpool(x)        
    x = self.relu(self.conv2(x))        
    x = self.maxpool(x)        
    x = self.relu(self.conv3(x))        
    x = self.relu(self.conv4(x))        
    x = self.relu(self.conv5(x))        
    x = self.maxpool(x)        
    x = self.avgpool(x)        
    x = x.view(x.size(0), 256 * 6 * 6)        
    x = self.relu(self.fc1(x))        
    x = self.relu(self.fc2(x))
    return self.fc3(x)
  
net = AlexNet() 

Training Convolutional Neural Networks

In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5),
                          (0.5, 0.5, 0.5))]
)

trainset = torchvision.datasets.CIFAR10(root = './data', train = True,
                                        download = True, transform = transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size= 128,
                                          shuffle = True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root = './data', train = False,
                                        download = True, transform = transform)

testloader = torch.utils.data.DataLoader(testset, batch_size= 128,
                                          shuffle = False, num_workers=2)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [ ]:
class Net(nn.Module):
  def __init__(self, num_classes=10):
    super(Net, self).__init__()        
    self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)          
    self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)        
    self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)         
    self.pool = nn.MaxPool2d((2, 2))        
    self.fc = nn.Linear(128 * 4 * 4, num_classes) 

  def forward(self, x):        
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = self.pool(F.relu(self.conv3(x)))
    x = x.view(-1,128*4*4) 
    return self.fc(x)
  

In [ ]:
net = Net() 
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr = 3e-4)

In [ ]:
# Training a CNN
j = 0
for epoch in range(10):
  print(j)
  j+=1
  for i, data in enumerate(trainloader,0):
    #Get the inputs
    inputs,  labels = data

    #Zero the parameter gradients
    optimizer.zero_grad()

    #Forward + backward + optimize
    outputs = net(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
  
print('Finished Training')

Finished Training


In [ ]:
#Evaluating the results

correct, total = 0, 0
predictions = []
net.eval()

for i, data in enumerate(testloader, 0):
  inputs, labels = data
  outputs = net(inputs)
  _, predicted = torch.max(outputs.data, 1)
  predictions.append(outputs)
  total += labels.size(0)
  correct += (predicted == labels).sum().item()

print('The testing set accuracy of the network is %d %%' %(100 * correct / total))

The testing set accuracy of the network is 70 %


The Sequential Module

In [ ]:
class AlexNet(nn.Module):

  def __init__(self, num_classes = 1000):
    super(AlexNet, self).__init__()
    self.features = nn.Sequential(
      nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2), 
      nn.ReLU(inplace=True),            
      nn.MaxPool2d(kernel_size=3, stride=2), 
      nn.Conv2d(64, 192, kernel_size=5, padding=2),            
      nn.ReLU(inplace=True), nn.MaxPool2d(kernel_size=3, stride=2),        
      nn.Conv2d(192, 384, kernel_size=3, padding=1),
      nn.ReLU(inplace=True),           
      nn.Conv2d(384, 256, kernel_size=3, padding=1),
      nn.ReLU(inplace=True),           
      nn.Conv2d(256, 256, kernel_size=3, padding=1),
      nn.ReLU(inplace=True),           
      nn.MaxPool2d(kernel_size=3, stride=2),)
    self.avgpool = nn.AdaptiveAvgPool2d((6, 6))        
    self.classifier = nn.Sequential(          
      nn.Dropout(), nn.Linear(256 * 6 * 6, 4096),
      nn.ReLU(inplace=True),                   
      nn.Dropout(), nn.Linear(4096, 4096), 
      nn.ReLU(inplace=True),
      nn.Linear(4096, num_classes),) 
  
#forward 
  def forward(self, x):      
    x = self.features(x)     
    x = self.avgpool(x)     
    x = x.view(x.size(0), 256 * 6 * 6)    
    x = self.classifier(x)
    return x


Validation sets in PyTorch

In [ ]:
indices = np.arange(50000)
np.random.shuffle(indices)

train_loader = torch.utils.data.DataLoader(
  torchvision.datasets.CIFAR10(root="./data", train=True, download= True, 
                   transform=transforms.Compose([Transforms.ToTensor(),
                    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0,224, 0.225))])),
                    batch_size =1, shuffle= False, sampler = torch.utils.data.SubsetRandomSampler(indices[:45000]))

val_loader = torch.utils.data.DataLoader(
  torchvision.datasets.CIFAR10(root="./data", train=True, download= True, 
                   transform=transforms.Compose([Transforms.ToTensor(),
                    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0,224, 0.225))])),
                    batch_size =1, shuffle= False, 
                    sampler = torch.utils.data.SubsetRandomSampler(indices[45000:50000]))




  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


Fine tuning in PyTorch

In [ ]:
model = Net()
#load parameters from the old model
model.load_state_dict(torch.load('cifar10_net.pth'))
#change the number of out channels
model.fc= nn.linear(4*4*1024, 100)
#Train and evaluate the model
model.train()

FileNotFoundError: ignored

In [ ]:
model = torchvision.models.resnet18(pretrained=True)
model.fc = nn.Linear(512, num_classes)

/usr/local/lib/python3.7/dist-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/usr/local/lib/python3.7/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

NameError: ignored